<h3>Novo Cartão de crédito</h3>
<br />

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('Financeiro',array('controller'=>'cartoes','action' => 'new')));
$form->prepare();
?>

<?php echo $this->form()->openTag($form);?>
<?php echo $this->formHidden($form->get('id'));?>
<div class="input-prepend input-append">
    <span class="add-on">Nome</span>
    <?php echo $this->formRow($form->get('descricao'))."<br /><br />";?>
</div>
<div class="input-prepend input-append">
    <span class="add-on">Vencimento</span>
    <?php echo $this->formRow($form->get('vencimento'))."<br /><br />";?>
</div>
<?php echo $this->formSubmit($form->get('submit'));?>
<?php echo $this->form()->closeTag();?>



        