<?php

namespace DoctrineORMModule\Proxy\__CG__\Financeiro\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Lancamentos extends \Financeiro\Entity\Lancamentos implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'id', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'valor', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'descricao', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'pagamento', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'vencimento', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'parcelas', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'arquivoBoleto', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'arquivoComprovante', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'status', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'idparcela', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'idrecorrente', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'transf', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'documento', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'tipo', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'user', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'periodo', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'cartegoria', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'conta', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'favorecido', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'centrocusto', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'cartao', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'competencia');
        }

        return array('__isInitialized__', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'id', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'valor', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'descricao', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'pagamento', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'vencimento', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'parcelas', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'arquivoBoleto', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'arquivoComprovante', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'status', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'idparcela', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'idrecorrente', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'transf', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'documento', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'tipo', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'user', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'periodo', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'cartegoria', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'conta', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'favorecido', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'centrocusto', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'cartao', '' . "\0" . 'Financeiro\\Entity\\Lancamentos' . "\0" . 'competencia');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Lancamentos $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getValor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValor', array());

        return parent::getValor();
    }

    /**
     * {@inheritDoc}
     */
    public function getDescricao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescricao', array());

        return parent::getDescricao();
    }

    /**
     * {@inheritDoc}
     */
    public function getPagamento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPagamento', array());

        return parent::getPagamento();
    }

    /**
     * {@inheritDoc}
     */
    public function getVencimento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVencimento', array());

        return parent::getVencimento();
    }

    /**
     * {@inheritDoc}
     */
    public function getParcelas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParcelas', array());

        return parent::getParcelas();
    }

    /**
     * {@inheritDoc}
     */
    public function getArquivoBoleto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArquivoBoleto', array());

        return parent::getArquivoBoleto();
    }

    /**
     * {@inheritDoc}
     */
    public function getArquivoComprovante()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArquivoComprovante', array());

        return parent::getArquivoComprovante();
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdparcela()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdparcela', array());

        return parent::getIdparcela();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdrecorrente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdrecorrente', array());

        return parent::getIdrecorrente();
    }

    /**
     * {@inheritDoc}
     */
    public function getTransf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransf', array());

        return parent::getTransf();
    }

    /**
     * {@inheritDoc}
     */
    public function getDocumento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocumento', array());

        return parent::getDocumento();
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', array());

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function getPeriodo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeriodo', array());

        return parent::getPeriodo();
    }

    /**
     * {@inheritDoc}
     */
    public function getCartegoria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCartegoria', array());

        return parent::getCartegoria();
    }

    /**
     * {@inheritDoc}
     */
    public function getConta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConta', array());

        return parent::getConta();
    }

    /**
     * {@inheritDoc}
     */
    public function getFavorecido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFavorecido', array());

        return parent::getFavorecido();
    }

    /**
     * {@inheritDoc}
     */
    public function getCentrocusto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCentrocusto', array());

        return parent::getCentrocusto();
    }

    /**
     * {@inheritDoc}
     */
    public function getCartao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCartao', array());

        return parent::getCartao();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setValor($valor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValor', array($valor));

        return parent::setValor($valor);
    }

    /**
     * {@inheritDoc}
     */
    public function setDescricao($descricao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescricao', array($descricao));

        return parent::setDescricao($descricao);
    }

    /**
     * {@inheritDoc}
     */
    public function setPagamento($pagamento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPagamento', array($pagamento));

        return parent::setPagamento($pagamento);
    }

    /**
     * {@inheritDoc}
     */
    public function setVencimento($vencimento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVencimento', array($vencimento));

        return parent::setVencimento($vencimento);
    }

    /**
     * {@inheritDoc}
     */
    public function setParcelas($parcelas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParcelas', array($parcelas));

        return parent::setParcelas($parcelas);
    }

    /**
     * {@inheritDoc}
     */
    public function setArquivoBoleto($arquivoBoleto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArquivoBoleto', array($arquivoBoleto));

        return parent::setArquivoBoleto($arquivoBoleto);
    }

    /**
     * {@inheritDoc}
     */
    public function setArquivoComprovante($arquivoComprovante)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArquivoComprovante', array($arquivoComprovante));

        return parent::setArquivoComprovante($arquivoComprovante);
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdparcela($idparcela)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdparcela', array($idparcela));

        return parent::setIdparcela($idparcela);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdrecorrente($idrecorrente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdrecorrente', array($idrecorrente));

        return parent::setIdrecorrente($idrecorrente);
    }

    /**
     * {@inheritDoc}
     */
    public function setTransf($transf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTransf', array($transf));

        return parent::setTransf($transf);
    }

    /**
     * {@inheritDoc}
     */
    public function setDocumento($documento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocumento', array($documento));

        return parent::setDocumento($documento);
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo(\Financeiro\Entity\Tipo $tipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', array($tipo));

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\Financeiro\Entity\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function setPeriodo(\Financeiro\Entity\Periodo $periodo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeriodo', array($periodo));

        return parent::setPeriodo($periodo);
    }

    /**
     * {@inheritDoc}
     */
    public function setCartegoria(\Financeiro\Entity\Cartegoria $cartegoria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCartegoria', array($cartegoria));

        return parent::setCartegoria($cartegoria);
    }

    /**
     * {@inheritDoc}
     */
    public function setConta(\Financeiro\Entity\Conta $conta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConta', array($conta));

        return parent::setConta($conta);
    }

    /**
     * {@inheritDoc}
     */
    public function setFavorecido(\Financeiro\Entity\Favorecido $favorecido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFavorecido', array($favorecido));

        return parent::setFavorecido($favorecido);
    }

    /**
     * {@inheritDoc}
     */
    public function setCentrocusto(\Financeiro\Entity\Centrocusto $centrocusto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCentrocusto', array($centrocusto));

        return parent::setCentrocusto($centrocusto);
    }

    /**
     * {@inheritDoc}
     */
    public function setCartao(\Financeiro\Entity\Cartao $cartao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCartao', array($cartao));

        return parent::setCartao($cartao);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompetencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompetencia', array());

        return parent::getCompetencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompetencia(\DateTime $competencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompetencia', array($competencia));

        return parent::setCompetencia($competencia);
    }

}
