<h3>Novo Cartegoria</h3>
<br />

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('Financeiro',array('controller'=>'cartegoria','action' => 'new')));
$form->prepare();
?>

<?php echo $this->form()->openTag($form);?>
<?php echo $this->formHidden($form->get('id'));?>
<div class="input-prepend input-append">
    <span class="add-on">Cartegoria</span>
    <?php echo $this->formRow($form->get('descricao'))."<br /><br />";?>
</div>
<div class="input-prepend input-append">
    <span class="add-on">Centro de Custo</span>
    <?php echo $this->formRow($form->get('centrocusto'))."<br /><br />";?>
</div>
<?php echo $this->formSubmit($form->get('submit'));?>
<?php echo $this->form()->closeTag();?>



        