<?php
$protocolo = (strpos(strtolower(filter_input(INPUT_SERVER, 'SERVER_PROTOCOL')), 'https') === false) ? 'http' : 'https';
?>
<script type="text/javascript">

    function exibeCartao() {
        if (document.getElementById('CAR1').style.display === 'none'){
            document.getElementById('CAR1').style.display = '';
        }else{
            document.getElementById('CAR1').style.display = 'none';
        }
    }
    function exibeTipo() {
        if(document.getElementById('tipo_id').value === '2'){
            document.getElementById('PER1').style.display = '';
            document.getElementById('PAR1').style.display = 'none';
        }else if(document.getElementById('tipo_id').value === '3'){
            document.getElementById('PER1').style.display = 'none';
            document.getElementById('PAR1').style.display = '';
        }else if(document.getElementById('tipo_id').value === '1'){
            document.getElementById('PER1').style.display = 'none';
            document.getElementById('PAR1').style.display = 'none';
        }
    }
    $(document).ready(function() {
        $("select[name=centrocusto]").change(function() {
            $("select[name=cartegoria]").html('<option value="">Carregando...</option>');
            $.post("<?php echo $protocolo . '://' . filter_input(INPUT_SERVER, 'HTTP_HOST') . $this->url('Financeiro', array('controller' => 'cartegoria', 'action' => 'listcartegorias')) ?>",
                    {centrocusto: $(this).val()},
            function(valor) {
                if(valor === ""){
                    $("select[name=cartegoria]").html('<option value="">Aguardando Centro de custo</option>'); 
                }else{
                    $("select[name=cartegoria]").html(valor);
                }
            }
            );
        });
    });
    $(document).ready(function() {
        $("select[name=centrocusto]").after(function() {
            $("select[name=cartegoria]").html('<option value="">Carregando...</option>');
            $.post("<?php echo $protocolo . '://' . filter_input(INPUT_SERVER, 'HTTP_HOST') . $this->url('FinanceiroAdmin', array('controller' => 'cartegoria', 'action' => 'listcartegorias')) ?>",
                    {cartegoria: $(this).val(),
                     centrocusto: $("select[name=centrocusto]").val()},
            function(valor) {
                if(valor === ""){
                    $("select[name=cartegoria]").html('<option value="">Aguardando Centro de custo</option>'); 
                }else{
                    $("select[name=cartegoria]").html(valor);
                }
            }
            );
        });
    });
</script>
<h3>Editar Despesa | Receita</h3>
<br />

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('Financeiro-edit', array('controller' => 'lancamentos', 'action' => 'edit')));
$form->prepare();
?>

<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formHidden($form->get('id')); ?>
<table>
    <tbody><tr>
            <td>
                <div class="input-prepend input-append">
                    <span class="add-on">Tipo de registro</span>
                    <?php echo $this->formRow($form->get('tipo')); ?>			
                </div>
            </td>
            <td></td>
            <td>
                <div class="input-prepend input-append">
                    <span class="add-on">Valor R$</span>
                    <?php echo $this->formRow($form->get('valor')); ?>
                </div>
            </td>
        </tr>
        <tr>
            <td colspan="3">
                <div class="input-prepend input-append">
                    <span class="add-on">Descrição</span>
                    <?php echo $this->formRow($form->get('descricao')); ?>
                    <span class="add-on">Nº Doc</span>
                    <?php echo $this->formRow($form->get('documento')); ?>
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="input-prepend input-append">
                    <span class="add-on">Vencimento</span>
                    <?php echo $this->formRow($form->get('vencimento')); ?>
                </div>
            </td>
            <td></td>
            <td>
                <div class="input-prepend input-append">
                    <span class="add-on">Lancar como</span>
                    <select class="span2" name="tipo_registro" id="tipo_registro1">
                        <option value="on">DEBITO</option>
                        <option value="off">RECEITA</option>
                    </select>
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="input-prepend input-append" id="PER1" style="display:none">
                    <span class="add-on">Período</span>
                    <?php echo $this->formRow($form->get('periodo')); ?>
                </div>
            </td>
            <td></td>
            <td>
                <div class="input-prepend input-append" id="PAR1" style="display:none">
                    <span class="add-on">Parcelas</span>
                    <?php echo $this->formRow($form->get('parcelas')); ?>
                </div>
            </td>

        </tr>
        <tr>
            <td>
                <div class="input-prepend input-append">
                    <span class="add-on">C.custo</span>
                    <?php echo $this->formRow($form->get('centrocusto')); ?>
                </div>
            </td>
            <td></td>
            <td>
                <div class="input-prepend input-append">
                    <span class="add-on">Cartegoria</span>
                    <?php echo $this->formRow($form->get('cartegoria')); ?>
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="input-prepend input-append">
                    <span class="add-on">Favorecido/Pagador</span>
                    <?php echo $this->formRow($form->get('favorecido')); ?>
                </div>
            </td>
            <td></td>
            <td>
                <div class="input-prepend input-append">
                    <span class="add-on">Debitar/Creditar</span>
                    <?php echo $this->formRow($form->get('conta')); ?>
                </div>
            </td>
        </tr>
        <tr>
            <td colspan="3">
                <div class="input-prepend input-append">
                    <span class="add-on">Lançar no Cartão de credito?&nbsp;<input type="checkbox" onchange='exibeCartao()' name="checa_cartao"></span>
                    <a id="CAR1" style="display:none">
                        <?php echo $this->formRow($form->get('cartao')); ?>
                    </a>
                </div>
            </td>
        </tr>
        <tr>
            <td colspan="3">
                <div class="input-prepend input-append">
                    <input name="boleto" id="boleto" type="file">
                    <span class="add-on">boleto</span>
                </div>
            </td>
        </tr>
        <tr>
            <td colspan="3">
                <div class="input-prepend input-append">
                    <input name="comp" id="comp" type="file">
                    <span class="add-on">Comprovante</span>
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="input-prepend input-append">
                    <?php echo $this->formRow($form->get('status')); ?>
                </div>
            </td>
        </tr>
    </tbody></table>

<?php echo $this->formSubmit($form->get('submit')); ?>
<?php echo $this->form()->closeTag();


