
    <h3>Lancamentos</h3>
    <a href="<?php echo $this->url('Financeiro',array('controller' => 'lancamentos', 'action' => 'new')); ?>"><img src="<?php echo $this->basePath('img/add.png') ?>" alt="Adicionar novo lancamento"/>&nbsp;Adicionar</a><br><br>
    <table class="table table-condensed table-hover">
        <thead>
            <tr>
                <td>Vencimento</td>
                <td>Pagamento</td>
                <td>Descrição</td>
                <td>Doc</td>
                <td>valor</td>
                <td>C.Custo</td>
                <td>Cartegoria</td>
                <td>Conta</td>
                <td>Fav./Pagador</td>
                <td>Status</td>
                <td></td>
                <td></td>
                <td></td>
                
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->lista as $lista):?>
            <?php 
                if ($lista->getValor() >= 0){
                    $cor = "green";
                }  else {
                    $cor = "red";
                }
            ?>
            <tr>
                <td><?php if($lista->getVencimento() instanceof \DateTime){echo $lista->getVencimento()->format("d/m/Y");}?></td>
                <td><?php if($lista->getPagamento() instanceof \DateTime){echo $lista->getPagamento()->format("d/m/Y");}?></td>
                <td><?php echo $lista->getDescricao();?></td>
                <td><?php echo $lista->getDocumento();?></td>
                <td><a style="color: <?php echo $cor; ?>">R$&nbsp;<?php echo number_format($lista->getValor(), 2, ',', '.');?></a></td>
                <td><?php echo $lista->getCentrocusto()->getDescricao();?></td>
                <td><?php echo $lista->getCartegoria()->getDescricao();?></td>
                <td><?php echo $lista->getConta()->getDescricao();?></td>
                <td><?php echo $lista->getFavorecido()->getDescricao();?></td>
                <td></td>
                <td><?php if($lista->getArquivoBoleto()):?>
                    <a href="<?php echo $this->url('Financeiro-edit',array ('controller' => 'lancamentos', 'action' => 'boleto', 'id' => $lista->getId()));?>" target="_blank"><img src="<?php echo $this->basePath('img/boleto.png') ?>" alt="Boleto"/></a>
                <?php endif;?>
                </td>
                <td><?php if($lista->getArquivoComprovante()):?>
                    <a href="<?php echo $this->url('Financeiro-edit',array ('controller' => 'lancamentos', 'action' => 'comprovante', 'id' => $lista->getId()));?>" target="_blank"><img src="<?php echo $this->basePath('img/comp.png') ?>" alt="Comprovante"/></a>
                <?php endif;?>
                </td>
                <td>
                    <a href="<?php echo $this->url('Financeiro-edit',array ('controller' => 'lancamentos', 'action' => 'edit', 'id' => $lista->getId()));?>"><img src="<?php echo $this->basePath('img/alterar.png') ?>" alt="Editar lançamento"/></a>&nbsp;&nbsp;&nbsp;
                    <a href="<?php echo $this->url('Financeiro-edit',array ('controller' => 'lancamentos', 'action' => 'delete', 'id' => $lista->getId()));?>"><img src="<?php echo $this->basePath('img/excluir.png') ?>" alt="Remover lançamento"/></a>
                </td>
            </tr>
            <?php endforeach;?>
        </tbody>
    </table>
    <br />
    <?php 
    echo $this->paginationControl($this->lista,'Sliding','paginator');
