<h3>Editando Ações</h3>
<br />

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('FinanceiroAdmin',array('controller'=>'acoes','action' => 'edit')));
$form->prepare();
?>

<?php echo $this->form()->openTag($form);?>
<?php echo $this->formHidden($form->get('id'));?>
<div class="input-prepend input-append">
    <span class="add-on">Ação</span>
    <?php echo $this->formRow($form->get('nome'))."<br /><br />";?>
</div>
<div class="input-prepend input-append">
    <span class="add-on">Descrição</span>
    <?php echo $this->formRow($form->get('descricao'))."<br /><br />";?>
</div>
<div class="input-prepend input-append">
    <span class="add-on">Módulo</span>
    <?php echo $this->formRow($form->get('controlador'))."<br /><br />";?>
</div>

<?php echo $this->formSubmit($form->get('submit'));?>
&nbsp;&nbsp;<a href="<?php echo $this->url('FinanceiroAdmin',array('controller' => 'acoes')); ?>" class="btn btn-danger">Cancelar</a>
<?php echo $this->form()->closeTag();?>



        