<h3>Nova ação</h3>
<br />

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('FinanceiroAdmin',array('controller'=>'acoes','action' => 'new')));
$form->prepare();
?>

<?php echo $this->form()->openTag($form);?>
<?php echo $this->formHidden($form->get('id'));?>
<div class="input-prepend input-append">
    <span class="add-on">Nome</span>
    <?php echo $this->formRow($form->get('nome'))."<br /><br />";?>
</div>
<div class="input-prepend input-append">
    <span class="add-on">Descrição</span>
    <?php echo $this->formRow($form->get('descricao'))."<br /><br />";?>
</div>
<div class="input-prepend input-append">
    <span class="add-on">Controller</span>
    <?php echo $this->formRow($form->get('controlador'))."<br /><br />";?>
</div>

<?php echo $this->formSubmit($form->get('submit'));?>
<?php echo $this->form()->closeTag();?>



        