<?php
$protocolo = (strpos(strtolower(filter_input(INPUT_SERVER, 'SERVER_PROTOCOL')), 'https') === false) ? 'http' : 'https';
?>
<script type="text/javascript">
    $(document).ready(function() {
        $("select[name=controlador]").change(function() {
            $("select[name=acoes]").html('<option value="">Carregando...</option>');
            $.post("<?php echo $protocolo . '://' . filter_input(INPUT_SERVER, 'HTTP_HOST') . $this->url('FinanceiroAdmin', array('controller' => 'acoes', 'action' => 'listacoes')) ?>",
                    {controlador: $(this).val()},
            function(valor) {
                $("select[name=acoes]").html(valor);
            }
            );
        });
    });
     $(document).ready(function() {
        $("select[name=acoes]").after(function() {
            $.post("<?php echo $protocolo . '://' . filter_input(INPUT_SERVER, 'HTTP_HOST') . $this->url('FinanceiroAdmin', array('controller' => 'acoes', 'action' => 'listacoes')) ?>",
                    {acoes: $(this).val(),
                     controlador: $("select[name=controlador]").val()},
            function(valor) {
                $("select[name=acoes]").html(valor);
            }
            );
        });
    });
</script>
<h3>Editando Permissões</h3>
<br />

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('FinanceiroAdmin', array('controller' => 'permissoes', 'action' => 'edit')));
$form->prepare();
?>

<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formHidden($form->get('id')); ?>

<div class="input-prepend input-append">
    <span class="add-on">Usuário</span>
    <?php echo $this->formRow($form->get('user')) . "<br /><br />"; ?>
</div>
<div class="input-prepend input-append">
    <span class="add-on">Módulos</span>
    <?php echo $this->formRow($form->get('controlador')) . "<br /><br />"; ?>
</div>
<div class="input-prepend input-append">
    <span class="add-on">Ações</span>
    <?php echo $this->formRow($form->get('acoes')) . "<br /><br />"; ?>
</div>

<?php echo $this->formSubmit($form->get('submit')); ?>
<?php echo $this->form()->closeTag();



