<h3>Editando Permissões</h3>
<br />

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('FinanceiroAdmin',array('controller'=>'permissoes','action' => 'edit')));
$form->prepare();
?>

<?php echo $this->form()->openTag($form);?>
<?php echo $this->formHidden($form->get('id'));?>

<div class="input-prepend input-append">
    <span class="add-on">Usuário</span>
    <?php echo $this->formRow($form->get('user'))."<br /><br />";?>
</div>
<div class="input-prepend input-append">
    <span class="add-on">Módulos</span>
    <?php echo $this->formRow($form->get('controlador'))."<br /><br />";?>
</div>
<div class="input-prepend input-append">
    <span class="add-on">Ações</span>
    <?php echo $this->formRow($form->get('acoes'))."<br /><br />";?>
</div>

<?php echo $this->formSubmit($form->get('submit'));?>
<?php echo $this->form()->closeTag();?>



        