<?php
//$urlPattern = $_SERVER['REQUEST_URI'];
$urlPattern = filter_input(INPUT_SERVER, 'REQUEST_URI');
$formatUrl= function ($page) use ($urlPattern) {
                if (!preg_match('/page/', $urlPattern)){
                    return $urlPattern . "/page/" . $page;
                }else{
                    return preg_replace('/\d/', $page, $urlPattern);
                }
            };
?>
<center>
<?php if ($this->pageCount): ?>
        <div class="paginationControl">
        <?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?> de <?php echo $this->totalItemCount; ?> registros
            <br />


            <!-- First page link -->
    <?php if (isset($this->previous)): ?>
                <a href="<?php echo $formatUrl($this->first) ?>"><img src="<?php echo $this->basePath('img/primeira.png'); ?>"></a>
    <?php else: ?>
                
                <span class="disabled"> <img src="<?php echo $this->basePath('img/primeiraDisabled.png') ?>"></span>
            <?php endif; ?>


            <!-- Previous page link -->
    <?php if (isset($this->previous)): ?>
                <a href="<?php echo $formatUrl($this->previous) ?>"><img src="<?php echo $this->basePath('img/anterior.png'); ?>"></a>
    <?php else: ?>
                <span class="disabled"><img src="<?php echo $this->basePath('img/anteriorDisabled.png') ?>"></span>
            <?php endif; ?>


            <!-- Next page link -->
    <?php if (isset($this->next)): ?>
                <a href="<?php echo $formatUrl($this->next); ?>"><img src="<?php echo $this->basePath('img/proximo.png'); ?>"></a>
    <?php else: ?>
                <span class="disabled"><img src="<?php echo $this->basePath('img/proximoDisabled.png') ?>"></span>
            <?php endif; ?>


            <!-- Last page link -->
    <?php if (isset($this->next)): ?>
                <a href="<?php echo $formatUrl($this->last); ?>"><img src="<?php echo $this->basePath('img/ultima.png'); ?>"></a>
    <?php else: ?>
                <span class="disabled"><img src="<?php echo $this->basePath('img/ultimaDisabled.png') ?>"></span>
            <?php endif; ?>

        </div>

<?php endif; ?>
</center>