<h3>Editar Centro de custo</h3>
<br />
<?php

$form = $this->form;

$form->setAttribute('action', $this->url('Financeiro-edit',array('controller'=>'centrocusto','action' => 'edit')));

$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('idf_centrocusto'));
echo $this->formRow($form->get('descricao'))."<br /><br />";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

