
    <h3>Centros de custo</h3>
    <a href="<?php echo $this->url('Financeiro',array('controller' => 'centrocusto', 'action' => 'new')); ?>"><img src="<?php echo $this->basePath('img/add.png') ?>" alt="Adicionar novo Centro de custo"/>&nbsp;Adicionar</a><br><br>
    <table class="table table-condensed table-hover">
        <thead>
            <tr>
                <td>ID</td>
                <td>Descrição</td>
                <td>Ações</td>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->centrosdecusto as $centroDeCusto):?>
            <tr>
                <td><?php echo $centroDeCusto->getIdfCentrocusto();?></td>
                <td><?php echo $centroDeCusto->getDescricao();?></td>
                <td>
                    <a href="<?php echo $this->url('Financeiro-edit',array ('controller' => 'centrocusto', 'action' => 'edit', 'id' => $centroDeCusto->getIdfCentrocusto()));?>"><img src="<?php echo $this->basePath('img/alterar.png') ?>" alt="Editar Centro de Custo"/></a>&nbsp;&nbsp;&nbsp;
                    <a href="<?php echo $this->url('Financeiro-edit',array ('controller' => 'centrocusto', 'action' => 'delete', 'id' => $centroDeCusto->getIdfCentrocusto()));?>"><img src="<?php echo $this->basePath('img/excluir.png') ?>" alt="Remover Centro de Custo"/></a>
                </td>
            </tr>
            <?php endforeach;?>
        </tbody>
    </table>
    <br />
    <?php 
    echo $this->paginationControl($this->centrosdecusto,'Sliding','paginator');
