<h3>Novo Centro de custo</h3>
<br />
<?php
$form = $this->form;

$form->setAttribute('action', $this->url('Financeiro',array('controller'=>'centrocusto','action' => 'new')));

$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('descricao'))."<br /><br />";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();


