<h3>Editar Centro de custo</h3>
<br />
<?php

$form = $this->form;

$form->setAttribute('action', $this->url('Financeiro-edit',array('controller'=>'centrocusto','action' => 'edit')));

$form->prepare();
?>

<?php echo $this->form()->openTag($form);?>
<?php echo $this->formHidden($form->get('idf_centrocusto'));?>
<div class="input-prepend input-append">
    <span class="add-on">Nome</span>
    <?php echo $this->formRow($form->get('descricao'))."<br /><br />";?>
</div>
<?php echo $this->formSubmit($form->get('submit'));?>
<?php echo $this->form()->closeTag();?>

