<h3>Editar status</h3>
<br />
<?php

$form = $this->form;

$form->setAttribute('action', $this->url('Financeiro-edit',array('controller'=>'ativo','action' => 'edit')));

$form->prepare();
?>

<?php echo $this->form()->openTag($form);?>
<?php echo $this->formHidden($form->get('id'));?>
<div class="input-prepend input-append">
    <span class="add-on">Nome</span>
    <?php echo $this->formRow($form->get('nome'))."<br /><br />";?>
</div>
<?php echo $this->formSubmit($form->get('submit'));?>
&nbsp;&nbsp;<a href="<?php echo $this->url('FinanceiroAdmin',array('controller' => 'ativo')); ?>" class="btn btn-danger">Cancelar</a>
<?php echo $this->form()->closeTag();?>

