
    <h3>Status</h3>
    <a href="<?php echo $this->url('Financeiro',array('controller' => 'ativo', 'action' => 'new')); ?>"><img src="<?php echo $this->basePath('img/add.png') ?>" alt="Adicionar novo ativo"/>&nbsp;Adicionar</a><br><br>
    <table class="table table-condensed table-hover">
        <thead>
            <tr>
                <td>ID</td>
                <td>Descrição</td>
                <td>Ações</td>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->lista as $lista):?>
            <tr>
                <td><?php echo $lista->getId();?></td>
                <td><?php echo $lista->getNome();?></td>
                <td>
                    <a href="<?php echo $this->url('Financeiro-edit',array ('controller' => 'ativo', 'action' => 'edit', 'id' => $lista->getId()));?>"><img src="<?php echo $this->basePath('img/alterar.png') ?>" alt="Editar ativo"/></a>&nbsp;&nbsp;&nbsp;
                    <a href="<?php echo $this->url('Financeiro-edit',array ('controller' => 'ativo', 'action' => 'delete', 'id' => $lista->getId()));?>"><img src="<?php echo $this->basePath('img/excluir.png') ?>" alt="Remover ativo"/></a>
                </td>
            </tr>
            <?php endforeach;?>
        </tbody>
    </table>
    <br />
    <?php 
    echo $this->paginationControl($this->lista,'Sliding','paginator');
