<h3>Editando Usuário</h3>
<br />

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('FinanceiroAdmin',array('controller'=>'user','action' => 'edit')));
$form->prepare();
?>

<?php echo $this->form()->openTag($form);?>
<?php echo $this->formHidden($form->get('id'));?>
<div class="input-prepend input-append">
    <span class="add-on">Username</span>
    <?php echo $this->formRow($form->get('username'))."<br /><br />";?>
</div>
<div class="input-prepend input-append">
    <span class="add-on">Senha</span>
    <?php echo $this->formRow($form->get('password'))."<br /><br />";?>
</div>
<div class="input-prepend input-append">
    <span class="add-on">Email</span>
    <?php echo $this->formRow($form->get('email'))."<br /><br />";?>
</div>
<div class="input-prepend input-append">
    <span class="add-on">Celular</span>
    <?php echo $this->formRow($form->get('celular'))."<br /><br />";?>
</div>
<div class="input-prepend input-append">
    <span class="add-on">Telefone</span>
    <?php echo $this->formRow($form->get('telefone'))."<br /><br />";?>
</div>
<div class="input-prepend input-append">
    <span class="add-on">Status</span>
    <?php echo $this->formRow($form->get('ativo'))."<br /><br />";?>
</div>

<?php echo $this->formSubmit($form->get('submit'));?>
&nbsp;&nbsp;<a href="<?php echo $this->url('FinanceiroAdmin',array('controller' => 'user')); ?>" class="btn btn-danger">Cancelar</a>
<?php echo $this->form()->closeTag();?>



        