<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('FinanceiroPessoal'); ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                       ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
                       ->prependStylesheet($this->basePath() . '/css/style.css')
                       ->prependStylesheet($this->basePath() . '/css/docs.css')
                       ->prependStylesheet($this->basePath() . '/css/bootstrap.responsive.css');
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',));
        ?>

    </head>
    <body>
    
        
        <nav class="navbar navbar-fixed-top" role="navigation">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="active">
                                <a href="#" class="disabled"><img src="<?php echo $this->basePath('img/Financeiro.png'); ?>">&nbsp;Sistema Financeiro</a>
                            </li>
                            <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Cadastros<b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <a href="<?php echo $this->url('Financeiro', array('controller' => 'ativo'));?>">Ativo</a>
                                        </li>
                                        <li>
                                            <a href="<?php echo $this->url('Financeiro', array('controller' => 'centrocusto'));?>">Centro de Custo</a>
                                        </li>
                                        <li>
                                            <a href="<?php echo $this->url('Financeiro', array('controller' => 'cartegoria'));?>">Cartegoria</a>
                                        </li>
                                         <li>
                                            <a href="<?php echo $this->url('Financeiro', array('controller' => 'user'));?>">Usuários</a>
                                        </li>
                                        <li>
                                            <a href="<?php echo $this->url('Financeiro', array('controller' => 'auth'));?>">Autenticar</a>
                                        </li>
                                        <li>
                                            <a href="<?php echo $this->url('FinanceiroAdmin', array('controller' => 'modulos'));?>">Modulos (Admin)</a>
                                        </li>
                                        <li>
                                            <a href="<?php echo $this->url('FinanceiroAdmin', array('controller' => 'acoes'));?>">Ações (Admin)</a>
                                        </li>
                                    </ul>
                            </li>
                            
                           <li>
                               <a href="<?php echo $this->url('FinanceiroAdmin', array('controller' => 'auth','action'=>'logout'));?>">Sair</a>          
                           </li>
                        </ul>
                    </div> 
                </div>
            </div>
        </nav>
    
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <center>
                <footer>
                    <p>&copy; 2005 - <?php echo date('Y') ?> InfoSay Tecnologia. <?php echo 'Todos os direitos reservados.' ?></p>
                </footer>
            </center>
        </div>
        <?php echo $this->inlineScript() ?>
    
        
    </body>
</html>
